### ISSUE TITLE
Segmentation fault on Unsafe.class.getDeclaredMethods() (stand-alone build)

### ISSUE THREAD

**Issue by wizzardo** [ReadyTalk/avian#398] opened 2015-01-16 15:50 UTC
environment: windows x86_64 lzma

**Comment by dicej** [comment] 2015-01-22 17:04
I'm not able to reproduce this with the code `System.out.println("method count is " + Unsafe.class.getDeclaredMethods().length);` -- it prints "method count is 57" and doesn't crash on Windows or Linux.  Can you provide a complete test case, including how you built Avian?

Thanks.

**Comment by wizzardo** [comment] 2015-01-22 18:49
git clone https://github.com/ReadyTalk/avian.git
git clone https://github.com/ReadyTalk/win64.git
cd avian/
git checkout v1.1
make lzma=../lzma openjdk=/cygdrive/c/open_jdk1.7u60/openjdk-1.7.0-u60-unofficial-windows-amd64-image openjdk-src=/cygdrive/c/open_jdk1.7u60/jdk7u60/jdk/src
mkdir hello
cd hello/
ar x ../build/windows-x86_64-lzma-openjdk-src/libavian.a
cp ../build/windows-x86_64-lzma-openjdk-src/classpath.jar boot.jar
nano Hello.java

cat Hello.java
public class Hello {
  public static void main(String[] args) {
    System.out.println("hello, world!");
	System.out.println("method count is " + sun.misc.Unsafe.class.getDeclaredMethods().length);
  }
}

/cygdrive/c/open_jdk1.7u60/openjdk-1.7.0-u60-unofficial-windows-amd64-image/bin/javac  Hello.java
/cygdrive/c/open_jdk1.7u60/openjdk-1.7.0-u60-unofficial-windows-amd64-image/bin/jar u0f boot.jar Hello.class

../build/windows-x86_64-lzma-openjdk-src/binaryToObject/binaryToObject.exe boot.jar boot.jar.o _binary_boot_jar_start _binary_boot_jar_end windows x86_64
x86_64-w64-mingw32-g++ -fno-exceptions -fno-rtti -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/win32"      -D_JNI_IMPLEMENTATION_ -c embedded-jar-main.cpp -o main.o
x86_64-w64-mingw32-dlltool -z hello.def *.o
x86_64-w64-mingw32-dlltool -d hello.def -e hello.exp
x86_64-w64-mingw32-gcc hello.exp *.o -L../../win64/lib -lmingwthrd -lm -lz -lws2_32     -lIphlpapi -mwindows -mconsole -o hello.exe

./hello.exe
hello, world!
Segmentation fault

**Comment by wizzardo** [comment] 2015-01-22 18:53
I tried build master branch but got
makefile:79: *** "'cygwin' is not a supported platform (choose one of: linux windows macosx ios freebsd)".  Stop.
also I reproduced segfault without lzma support in avian

**Comment by dicej** [comment] 2015-01-22 19:06
Thanks for the info.  The cygwin problem is fixed in https://github.com/ReadyTalk/avian/pull/402, and https://github.com/ReadyTalk/avian/pull/403 should fix the original issue.

**Comment by wizzardo** [comment] 2015-01-22 19:13
thank you for your awesome work =)

**Closed** 2015-01-22 20:38 UTC
